kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("service.urls", namespace="service")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("registration/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "kitchen"

service/urls.py

from django.urls import path

from service import views
from service.views import (
    index,
    DishTypesListView,
    CookListView,
    DishListView,
    DishDetailView,
    CooksCreateView,
    DishCreateView,
    DishTypesCreateView,
    DishUpdateView,
    DishDeleteView,
    CooksUpdateView,
    CooksDeleteView,
    DishTypesUpdateView,
    DishTypesDeleteView,
    CooksDetailView,
    IngredientListView,
    IngredientUpdateView,
    IngredientDeleteView,
    IngredientCreateView,

)

urlpatterns = [
    path("", index, name="index"),
    path("dish_types/", DishTypesListView.as_view(), name="dish_type_list"),
    path("dish_types/create/", DishTypesCreateView.as_view(), name="dish_type_create"),
    path("dish_types/<int:pk>/update/", DishTypesUpdateView.as_view(), name="dish_type_update"),
    path("dish_types/<int:pk>/delete/", DishTypesDeleteView.as_view(), name="dish_type_delete"),
    path("cooks/", CookListView.as_view(), name="cook_list"),
    path("cooks/create/", CooksCreateView.as_view(), name="cook_create"),
    path("cooks/<int:pk>/", CooksDetailView.as_view(), name="cook_detail"),
    path("cooks/<int:pk>/update/", CooksUpdateView.as_view(), name="cook_update"),
    path("cooks/<int:pk>/delete/", CooksDeleteView.as_view(), name="cook_delete"),
    path("dishs/", DishListView.as_view(), name="dish_list"),
    path("dishs/<int:pk>/", DishDetailView.as_view(), name="dish_detail"),
    path("dishs/<int:pk>/update/", DishUpdateView.as_view(), name="dish_update"),
    path("dishs/<int:pk>/delete/", DishDeleteView.as_view(), name="dish_delete"),
    path("dishs/create/", DishCreateView.as_view(), name="dish_create"),
    path("dishs/<int:pk>/update/ingredient/", IngredientListView.as_view(), name="dish_ingredient_list"),
    path("dishs/<int:pk>/update/ingredient/create/", IngredientCreateView.as_view(), name="dish_ingredient_create"),
    path("dishs/<int:dish_pk>/update/ingredient/<int:pk>/update/", IngredientUpdateView.as_view(), name="dish_ingredient_update"),
    path("dishs/<int:dish_pk>/update/ingredient/<int:pk>/delete/", IngredientDeleteView.as_view(), name="dish_ingredient_delete"),

]

app_name = "service"

service/models.py
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.db import models


class DishType(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, max_length=8, decimal_places=2)
    dish_type = models.ForeignKey(
        DishType,
        on_delete=models.CASCADE,
        related_name="dishes"
    )
    cooks = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="dishes")

    class Meta:
        ordering = ("name",)

    def __str__(self, ):
        return f"{self.name} (cooks: {self.cooks}, dish description:{self.description})"


class Ingredient(models.Model):
    name = models.CharField(max_length=255)
    UNIT_CHOICES = [
        ("g", "grams"),
        ("ml", "milliliters"),
        ("th", "Thing"),
        ("te.sp.", "teaspoon"),
        ("tb.sp.", "tablespoon"),
        ("gl", "glass"),
    ]
    unit = models.CharField(max_length=15, choices=UNIT_CHOICES)
    quantity = models.DecimalField(max_digits=7, decimal_places=2)
    dish = models.ForeignKey(Dish, on_delete=models.CASCADE, related_name="ingredients")

    class Meta:
        ordering = ("name",)

    def __str__(self):
        return f"{self.name} ({self.quantity} {self.unit})"


class Cook(AbstractUser):
    year_of_experience = models.IntegerField(blank=False, null=True)
    POSITION_CHOICES = [
        ("SH", "Chef"), ("SS", "Sous Chef"),
        ("PG", "Hot Shop Cook"), ("PH", "Cold Shop Cook"),
        ("PK", "Pastry Chef"), ("PZ", "Procurement Chef"),
        ("PL", "Line Cook"), ("ST", "Stuart"),
    ]
    position = models.CharField(max_length=2, blank=False, null=False, choices=POSITION_CHOICES)

    class Meta:
        ordering = ("username",)

    def __str__(self):
        return f"{self.username}: ({self.first_name} {self.last_name})"

service/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


from service.models import Cook, Dish, Ingredient


class CooksCreationForm(UserCreationForm):

    class Meta(
        UserCreationForm.Meta
    ):
        model = Cook
        fields = UserCreationForm.Meta.fields + ("first_name", "last_name", "position",)


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Dish
        fields = "__all__"


class CooksSearchForm(forms.Form):
    username = forms.CharField(
        # max_lenght=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username..."}))


class DishSearchForm(forms.Form):
    name = forms.CharField(
        # max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."}))

service/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.http import HttpRequest, HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views import generic
from service.forms import CooksCreationForm, DishForm
from service.models import Dish, Cook, DishType, Ingredient
from .forms import (
    CooksSearchForm,
    DishSearchForm,
)

def index(request: HttpRequest) -> HttpResponse:
    num_dishs = Dish.objects.count()
    num_cooks = Cook.objects.count()
    num_dish_type = DishType.objects.count()
    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1
    context = {
        "num_dishs": num_dishs,
        "num_cooks": num_cooks,
        "num_dish_type": num_dish_type
    }

    return render(request, "service/index.html", context=context)


class DishTypesListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    template_name = "service/dish_type_list.html"
    context_object_name = "dish_type_list"
    paginate_by = 5


class DishTypesCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    template_name = "service/dish_type_list_form.html"
    success_url = reverse_lazy("service:dish_type_list")
    fields = "__all__"


class DishTypesUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    template_name = "service/dish_type_list_form.html"
    success_url = reverse_lazy("service:dish_type_list")
    fields = "__all__"


class DishTypesDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    template_name = "service/dish_type_list_delete.html"
    success_url = reverse_lazy("service:dish_type_list")


class IngredientListView(LoginRequiredMixin, generic.ListView):
    model = Ingredient
    template_name = "service/dish_ingredient_list.html"
    context_object_name = "dish_ingredient_list"
    paginate_by = 10

    def get_queryset(self):
        dish_pk = self.kwargs.get("pk")
        return Ingredient.objects.filter(dish=dish_pk)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        dish_pk = self.kwargs.get("pk")
        dish = get_object_or_404(Dish, pk=dish_pk)
        context["object"] = dish

        INGREDIENT_URL = reverse("service:dish_ingredient_list", kwargs={'pk': dish_pk})
        context["INGREDIENT_URL"] = INGREDIENT_URL

        return context


class IngredientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Ingredient
    template_name = "service/dish_ingredient_list_form.html"
    success_url = reverse_lazy("service:dish_ingredient_list")
    fields = ["name", "unit", "quantity"]

    def get_success_url(self):
        dish_pk = self.kwargs.get("dish_pk")
        return reverse("service:dish_ingredient_list", kwargs={"pk": dish_pk})


class IngredientCreateView(LoginRequiredMixin, generic.CreateView):
    model = Ingredient
    template_name = "service/dish_ingredient_list_form.html"

    fields = ["name", "unit", "quantity"]

    def get_success_url(self):
        dish_pk = self.kwargs.get("pk")
        return reverse("service:dish_ingredient_list", kwargs={"pk": dish_pk})

    def form_valid(self, form):
        ingredient = form.save(commit=False)
        dish_pk = self.kwargs.get("pk")
        dish = get_object_or_404(Dish, pk=dish_pk)
        ingredient.dish = dish
        ingredient.save()
        return HttpResponseRedirect(self.get_success_url())


class IngredientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Ingredient
    template_name = "service/dish_ingredient_delete.html"
    success_url = reverse_lazy("service:dish_ingredient_list")

    def get_success_url(self):
        dish_pk = self.kwargs.get("dish_pk")
        return reverse("service:dish_ingredient_list", kwargs={"pk": dish_pk})


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    template_name = "service/cook_list.html"
    context_object_name = "cook_list"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CookListView, self).get_context_data(**kwargs)

        username = self.request.GET.get("username", "")
        context["search_form"] = CooksSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        self.queryset = super(CookListView, self).get_queryset()
        username = self.request.GET.get("username")

        if username:
            return self.queryset.filter(username__icontains=username)
        return self.queryset


class CooksCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    fields = ("first_name", "last_name", "username", "password", "year_of_experience", "position",)
    success_url = reverse_lazy("service:cook_list")
    template_name = "service/cook_list_form.html"


class CooksDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook


class CooksUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = ("first_name", "last_name", "username", "password", "year_of_experience", "position",)
    success_url = reverse_lazy("service:cook_list")
    template_name = "service/cook_list_form.html"


class CooksDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    template_name = "service/cook_list_form_delete.html"
    success_url = reverse_lazy("service:cook_list")


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    template_name = "service/dish_list.html"
    paginate_by = 10

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(DishListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.select_related("dish_type")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__contains=form.cleaned_data["name"])
        return queryset


class DishDetailView(generic.DetailView):
    model = Dish
    paginate_by = 10


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    success_url = reverse_lazy("service:dish_list")
    template_name = "service/dish_list_form.html"
    form_class = DishForm


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    success_url = reverse_lazy("service:dish_list")
    template_name = "service/dish_list_form.html"
    form_class = DishForm


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    template_name = "service/dish_list_config_delete.html"
    success_url = reverse_lazy("service:dish_list")





templates/service/cook_detail.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Username: {{ cook.username }}</h1>
  <p><strong>First name:</strong> {{ cook.first_name }}</p>
  <p><strong>Last name:</strong> {{ cook.last_name }}</p>
  <p><strong>Position: </strong>{{ cook.get_position_display }}</p>
  <p><strong>Year_of_experience: </strong>{{ cook.year_of_experience }}</p>
  <p><strong>Author of the dishes: </strong></p>
  {% for dish in cook.dishes.all %}
    <hr>
    <p class="text-muted">{{ dish.id }}</p>
    <p> {{ dish.name }} - {{ dish.dish_type }}</p>
  {% empty %}
    <p>No dish!</p>
  {% endfor %}
{% endblock %}

templates/service/cook_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<head>
  <h1>Our Chefs:<a href="{% url 'service:cook_create' %}" class="btn btn-primary link-to-page" style="float: right">Add
    a shef</a></h1>
  <form method="get" action="" class="form-inline" style="float: left; margin-right: 30px">
    {{ search_form|crispy }}
    <input class="btn btn" type="submit" value="🔎">
  </form>
  {% if cook_list %}
  <table class="table">
    <tr>
      <th>ID</th>
      <th>POSITION</th>
      <th>FIRST NAME</th>
      <th>LAST NAME</th>
      <th>UPDATE</th>
      <th>DELETE</th>
    </tr>
    <tr>
      {% for cook in cook_list %}
      <td>
        <a href="{% url 'service:cook_detail' pk=cook.id %} ">{{ cook.id }}</a>
      </td>
      <td>
        {{ cook.position }}
      </td>
      <td>
        {{ cook.first_name }}
      </td>
      <td>
        {{ cook.last_name }}
      </td>
      <td>
        <a href="{% url 'service:cook_update' pk=cook.id %}">Update</a>
      </td>
      <td>
        <a href="{% url 'service:cook_delete' pk=cook.id %} ">Delete</a>
      </td>
    </tr>
    {% endfor %}
  </table>
  {% else %}
  <p> Thera are no dish type</p>
  {% endif %}
  {% load query_transform %}
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
    </li>
    {% endif %}
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }} </span>
    </li>
    {% if page_obj.has_next %}
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
</head>
{% endblock %}

templates/service/cook_list_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Cook:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/service/dish_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>Name of the dish: {{ dish.name }}</h1>
  <p><strong>Dish type: </strong>{{ dish.dish_type.name }}</p>
  <p><strong>Description: </strong>{{ dish.description }}</p>
  <p><strong>Ingredients: </strong>
    {% for ingredient in dish.ingredients.all %}</p>
      <hr>
      <p class="text-muted">{{ ingredient.id }}</p>
      <p> {{ ingredient.name }} - {{ ingredient.quantity }} {{ ingredient.unit }}  </p>
    {% endfor %}
  <p><strong>Cooks: </strong>
    {% for cook in dish.cooks.all %}</p>
      <hr>
      <p class="text-muted">{{ cook.id }}</p>
      <p> {{ cook.first_name }} {{ cook.last_name }}</p>
    {% empty %}
      <p>No cooks!</p>
    {% endfor %}
{% endblock %}

templates/service/dish_ingredient_delete.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Delete ingredient</h1>
  <p> Are you sure you want to delete in this ingredients: {{ ingredient.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>
{% endblock %}

templates/service/dish_ingredient_list.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Ingredients:
    {% if object %}
      <a href="{% url 'service:dish_ingredient_create' object.pk %}"
         style="float: right" class="btn btn-primary link-to-page">Add new ingredient
    {% endif %}
    </a>
  </h1>
  {% if dish_ingredient_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Unit</th>
        <th>Quantity</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      <tr>
        {% for ingredient in dish_ingredient_list %}
          <td>
            {{ ingredient.id }}
          </td>
          <td>
            {{ ingredient.name }}
          </td>
          <td>
            {{ ingredient.quantity }}
          </td>
          <td>
            {{ ingredient.unit }}
          </td>
          <td>
            <a href="{% url 'service:dish_ingredient_update' dish_pk=object.pk pk=ingredient.id %}">Update</a>
          </td>
          <td>
            <a href="{% url 'service:dish_ingredient_delete' dish_pk=object.pk pk=ingredient.id %} ">Delete</a>
          </td>
          </tr>
        {% endfor %}
    </table>
  {% else %}
    <p> Thera are no ingredients</p>
  {% endif %}
  {% load query_transform %}
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
    </li>
    {% endif %}
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }} </span>
    </li>
    {% if page_obj.has_next %}
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
{% endblock %}

templates/service/dish_ingredient_list_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Ingredient:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/service/dish_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
<h1>Our Dish:<a href="{% url 'service:dish_create' %}" style="float: right" class="btn btn-primary link-to-page"
>Add new dish</a></h1>
<form method="get" action="" class="form-inline" style="float: left; margin-right: 30px">
  {{ search_form|crispy }}
  <input class="btn btn" type="submit" value="🔎">
</form>
{% if dish_list %}
<table class="table">
  <tr>
    <th>ID</th>
    <th>NAME</th>
    <th>TYPE</th>
    <th>UPDATE</th>
    <th>DELETE</th>
  </tr>
  <tr>
    {% for dish in dish_list %}
    <td>
      {{ dish.id }}
    </td>
    <td>
      <a href="{% url 'service:dish_detail' pk=dish.id %}">
        {{ dish.name }}
        {% for cook in dish.cooks.all %}
        {% if cook.id == user.id %}
        (Me)
        {% endif %}
        {% endfor %}
      </a>
    </td>
    <td>
      {{ dish.dish_type }}
    </td>
    <td>
      <a href="{% url 'service:dish_update' pk=dish.id %} ">Update</a>
    </td>
    <td>
      <a href="{% url 'service:dish_delete' pk=dish.id %} ">Delete</a>
    </td>
  </tr>
  {% endfor %}
</table>
{% else %}
<p> Thera are no dish </p>
{% endif %}
{% load query_transform %}
{% if is_paginated %}
<ul class="pagination">
  {% if page_obj.has_previous %}
  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
  </li>
  {% endif %}
  <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }} </span>
  </li>
  {% if page_obj.has_next %}
  <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
  </li>
  {% endif %}
</ul>
{% endif %}

{% endblock %}

templates/service/dish_list_config_delete.html
{% extends "layouts/base.html" %}
{% block content %}
  <h1>Delete dish</h1>
  <p> Are you sure you want to delete in this dish: {{ dish.name }}?</p>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>
{% endblock %}

templates/service/dish_list_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    {% if object %}
      <p> Ingredients:</p>
      <a href="{% url 'service:dish_ingredient_list' object.pk %}"
         class="btn btn-primary">{{ object|yesno:"Update,Add" }} Ingredients</a>
    {% endif %}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}

templates/service/dish_type_list.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Dish Type:<a href="{% url 'service:dish_type_create' %}" style="float: right" class="btn btn-primary link-to-page"
                   style="float: right">Add new dish type</a></h1></h1>

  {% if dish_type_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>NAME</th>
        <th>UPDATE</th>
        <th>DELETE</th>
      </tr>
      <tr>
        {% for dish_type in dish_type_list %}
          <td>
            {{ dish_type.id }}
          </td>
          <td>
            {{ dish_type.name }}
          </td>
          <td>
            <a href="{% url 'service:dish_type_update' pk=dish_type.id %}">Update</a>
          </td>
          <td>
            <a href="{% url 'service:dish_type_delete' pk=dish_type.id %} ">Delete</a>
          </td>
          </tr>
        {% endfor %}
    </table>
  {% else %}
    <p> Thera are no dish type</p>
  {% endif %}
{% load query_transform %}
  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
    </li>
    {% endif %}
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }} </span>
    </li>
    {% if page_obj.has_next %}
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}

{% endblock %}

templates/service/dish_type_list_delete.html
{% extends "layouts/base.html" %}
{% block content %}
   <h1>Delete dish type</h1>
  <p> Are you sure you want to delete in this dish type: {{ dishtype.name}}?</p>
  <form action="" method="post">
  {% csrf_token%}
  <input type="submit" value="Yes, delete" class="btn btn-danger" />
  </form>
{% endblock %}

templates/service/dish_type_list_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} New Dish Type:</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Submit">
  </form>
{% endblock %}