kitchen/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("service.urls", namespace="service")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("registration/", include("django.contrib.auth.urls")),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app_name = "kitchen"

service/urls.py

from django.urls import path

from service import views
from service.views import (
    index,
    DishTypesListView,
    CookListView,
    DishListView,
    DishDetailView,
    CooksCreateView,
    DishCreateView,
    DishTypesCreateView,
    DishUpdateView,
    DishDeleteView,
    CooksUpdateView,
    CooksDeleteView,
    DishTypesUpdateView,
    DishTypesDeleteView,
    CooksDetailView,
    IngredientListView,
    IngredientUpdateView,
    IngredientDeleteView,
    IngredientCreateView,

)

urlpatterns = [
    path("", index, name="index"),
    path("dish_types/", DishTypesListView.as_view(), name="dish_type_list"),
    path("dish_types/create/", DishTypesCreateView.as_view(), name="dish_type_create"),
    path("dish_types/<int:pk>/update/", DishTypesUpdateView.as_view(), name="dish_type_update"),
    path("dish_types/<int:pk>/delete/", DishTypesDeleteView.as_view(), name="dish_type_delete"),
    path("cooks/", CookListView.as_view(), name="cook_list"),
    path("cooks/create/", CooksCreateView.as_view(), name="cook_create"),
    path("cooks/<int:pk>/", CooksDetailView.as_view(), name="cook_detail"),
    path("cooks/<int:pk>/update/", CooksUpdateView.as_view(), name="cook_update"),
    path("cooks/<int:pk>/delete/", CooksDeleteView.as_view(), name="cook_delete"),
    path("dishs/", DishListView.as_view(), name="dish_list"),
    path("dishs/<int:pk>/", DishDetailView.as_view(), name="dish_detail"),
    path("dishs/<int:pk>/update/", DishUpdateView.as_view(), name="dish_update"),
    path("dishs/<int:pk>/delete/", DishDeleteView.as_view(), name="dish_delete"),
    path("dishs/create/", DishCreateView.as_view(), name="dish_create"),
    path("dishs/<int:pk>/update/ingredient/", IngredientListView.as_view(), name="dish_ingredient_list"),
    path("dishs/<int:pk>/update/ingredient/create/", IngredientCreateView.as_view(), name="dish_ingredient_create"),
    path("dishs/<int:dish_pk>/update/ingredient/<int:pk>/update/", IngredientUpdateView.as_view(), name="dish_ingredient_update"),
    path("dishs/<int:dish_pk>/update/ingredient/<int:pk>/delete/", IngredientDeleteView.as_view(), name="dish_ingredient_delete"),

]

app_name = "service"

templates/includes/footer.html
<!-- -------- START FOOTER 5 w/ DARK BACKGROUND ------- -->
<footer class="footer py-5">
  <div class="container z-index-1 position-relative">
    <div class="row">
      <div class="col-lg-4 me-auto mb-lg-0 mb-4 text-lg-start text-center">
        <h6 class="text-dark font-weight-bolder text-uppercase mb-lg-4 mb-3">Material Design</h6>
        <ul class="nav flex-row ms-n3 justify-content-lg-start justify-content-center mb-4 mt-sm-0">
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com/presentation?AFFILIATE=128200" target="_blank">
              About
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com/blog?AFFILIATE=128200" target="_blank">
              Blog
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-dark opacity-8" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">
              Services
            </a>
          </li>
        </ul>
        <p class="text-sm text-dark opacity-8 mb-0">
          &copy; <a href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed.
        </p>
      </div>
      <div class="col-lg-6 ms-auto text-lg-end text-center">
        <p class="mb-5 text-lg text-dark font-weight-bold">
          The reward for getting on the stage is fame. The price of fame is you can’t get off the stage.
        </p>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-dribbble"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-twitter"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark me-xl-4 me-4 opacity-5">
          <span class="fab fa-pinterest"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-dark opacity-5">
          <span class="fab fa-github"></span>
        </a>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_background.html
{% load static %}

<footer class="footer pt-5 mt-5">
  <hr class="horizontal dark mb-5">
  <div class="container">
    <div class=" row">
      <div class="col-md-3 mb-4 ms-auto">
        <div>
          <h6 class="text-gradient text-primary text-sm">Our social networks:</h6>
        </div>
        <div>
          <br>
              <a class="nav-link pe-1" href="https://github.com/creativetimofficial" target="_blank">
                <i class="fab fa-github text-lg opacity-8"></i>
              </a>
        </div>
      </div>
      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-gradient text-primary text-sm">Hours</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
                <br>
              </a>
            </li>

            <li class="nav-item">
                Tuesday – Sunday<br>12 - 9 pm
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://www.creative-tim.com/templates/premium?AFFILIATE=128200" target="_blank">
               <br>
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://www.creative-tim.com/blog?AFFILIATE=128200" target="_blank">
                <br>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-gradient text-primary text-sm">Palo Alto</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="https://iradesign.io/" target="_blank">
                <br>
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank">
                530 Bryant St, <br>Palo Alto, CA
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank">
                <br>
              </a>
            </li>
             <li class="nav-item">
              <a target="_blank">
                (095) 600-0433
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4">
        <div>
          <h6 class="text-gradient text-primary text-sm">Los Altos</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="https://www.creative-tim.com/contact-us?AFFILIATE=128200" target="_blank">
                <br>
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank">
               325 Main St,<br>Los Altos, CA
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank">
                <br>
              </a>
            </li>
            <li class="nav-item">
              <a target="_blank">
                (650) 699-0334
              </a>
            </li>

          </ul>
        </div>
      </div>

      <div class="col-md-2 col-sm-6 col-6 mb-4 me-auto">
        <div>
          <h6 class="text-gradient text-primary text-sm">More contacts</h6>
          <ul class="flex-column ms-n3 nav">
            <li class="nav-item">
              <a class="nav-link" href="https://www.creative-tim.com/terms?AFFILIATE=128200" target="_blank">
                <br>
              </a>
            </li>

            <li class="nav-item">
              <a target="_blank">
                eat@kitchenunity.com
              </a>
            </li>

            <li class="nav-item">
              <a class="nav-link" href="https://www.creative-tim.com/license?AFFILIATE=128200" target="_blank">
                <br>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="col-12">
        <div class="text-center">
          <p class="my-4 text-sm">
            &copy; <a href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed.
          </p>
        </div>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_fullscreen.html
{% load static %}

<footer class="footer py-5">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 mb-4 mx-auto text-center">
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Company
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          About Us
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Team
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Products
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Blog
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-5 me-3 mb-sm-0 mb-2">
          Pricing
        </a>
      </div>
      <div class="col-lg-8 mx-auto text-center mb-4 mt-2">
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-dribbble"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-twitter"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-instagram"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-pinterest"></span>
        </a>
        <a href="javascript:;" target="_blank" class="text-secondary me-xl-4 me-4">
          <span class="text-lg fab fa-github"></span>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="col-8 mx-auto text-center mt-1">
        <p class="mb-0 text-secondary">
          &copy; <a href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed.
        </p>
      </div>
    </div>
  </div>
</footer>

templates/includes/footer_signin.html
<footer class="footer position-absolute bottom-2 py-2 w-100">
  <div class="container">
    <div class="row align-items-center justify-content-lg-between">
      <div class="col-12 col-md-6 my-auto">
        <div class="copyright text-center text-sm text-white text-lg-start">
          &copy; <a class="font-weight-bold text-white" href="https://www.creative-tim.com?AFFILIATE=128200" target="_blank">Creative Tim</a> - Coded by AppSeed. 
        </div>
      </div>
      <div class="col-12 col-md-6">
        <ul class="nav nav-footer justify-content-center justify-content-lg-end">
          <li class="nav-item">
            <a href="https://www.creative-tim.com?AFFILIATE=128200" class="nav-link text-white" target="_blank">Creative Tim</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/presentation?AFFILIATE=128200" class="nav-link text-white" target="_blank">About Us</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/blog?AFFILIATE=128200" class="nav-link text-white" target="_blank">Blog</a>
          </li>
          <li class="nav-item">
            <a href="https://www.creative-tim.com/license?AFFILIATE=128200" class="nav-link pe-0 text-white" target="_blank">License</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</footer>

templates/includes/pagination.html
{% extends "layouts\base.html" %}
{% load crispy_forms_filters %}

{% block content %}
{% load query_transform %}

  {% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
    <a class="page-link" href="?page={{ page_obj.previous_page_number }}">prev</a>
    </li>
    {% endif %}
    <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }} </span>
    </li>
    {% if page_obj.has_next %}
    <a class="page-link" href="?page={{ page_obj.next_page_number }}">next</a>
    </li>
    {% endif %}
  </ul>
  {% endif %}
{% endblock %}

templates/includes/scripts.html
  {% load static %}
  
<!-- Core JS Files -->
<script src="{% static 'js/core/popper.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/core/bootstrap.min.js' %}" type="text/javascript"></script>
<script src="{% static 'js/plugins/perfect-scrollbar.min.js' %}"></script>

<!-- Plugins -->
<script src="{% static 'js/plugins/parallax.min.js' %}"></script>
<script src="{% static 'js/plugins/choices.min.js' %}"></script>
<script src="{% static 'js/plugins/countup.min.js' %}"></script>
<script src="{% static 'js/plugins/prism.min.js' %}"></script>
<script src="{% static 'js/plugins/flatpickr.min.js' %}"></script>
<script src="{% static 'js/plugins/moment.min.js' %}"></script>
<script src="{% static 'js/plugins/rellax.min.js' %}"></script>
<script src="{% static 'js/plugins/tilt.min.js' %}"></script>
<script src="{% static 'js/plugins/typedjs.js' %}"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>

<script src="{% static 'js/soft-design-system.min.js' %}" type="text/javascript"></script>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
{% if user.is_authenticated %}
  <li class="list-group-item">
    User: {{ user.username }}
  </li>
  <li class="list-group-item">
    <a href="{% url 'logout' %}">Logout</a>
  </li>
{% else %}
   <li class="list-group-item">
    <a href="{% url 'login' %}">Login</a>
  </li>
{% endif %}
<br>
   <li class="list-group-item">
    <a href="{% url 'service:index' %}">Home</a>
  </li>
   <li class="list-group-item">
    <a href="{% url 'service:dish_list' %}">All Dish</a>
  </li>
   <li class="list-group-item">
    <a href="{% url 'service:cook_list' %}">All cooks</a>
  </li>
   <li class="list-group-item">
    <a href="{% url 'service:dish_type_list' %}">All Dish Type</a>
  </li>
</ul>